* Goals
      ** Comment system:
        -- Facebook/reddit?
      ** try to co-opt someone per article to read it from an outside group, to prevent groupthink
      ** make description field 500 characters, blurb 100 characters. organize legacyarticles such that we truncate their descriptions to the correct size, then from now on, strong enforcement of size.
      ** in post-instruction.tex add style guide for references, in-line lists, using e.g. <h3> tags (###) for section titles, where to put captions, etc.
      ALICE ** move facebook like and twitter buttons to the post itself, and make them point to each specific article instead of to the webpage as a whole
            -- global dish on science like button should take you to dish on science facebook page, make it
            -- make facebook page
            -- for each article, have a like button with reasonably preompleted text/image
            -- twitter button should go to twitter page
            -- article should be shareable via twitter
            -- add a "share on reddit" button
      ALICE ** split long author names across two lines
            -- the author lists with many authors look ugly when width of screen gets small, figure out how to reflow
      KYLE ** pagination.
      KYLE ** Science Dictionary
        -- on desktop, we want definition to pop up in "right of article" div
        -- on mobile, we probably want to pop out a pre-loaded div below the word of interest
      BRUNO ** Put this shit on github
            --DONE-- make author names show up on mobile
            -- popular posts image sizes are heterogenous
            -- actual names are used in post template intead of nicknames, whoops
            -- add the correct afs permissions hooks after the article is added to the website
            -- Search box
            -- make a page to look at a specific author's articles, with optional bio at top
            -- hook up author name links wherever the author name appears


* coding todo's
  author headshot_src, allow images to be provided with article
  split relevant code from fix headshot src to fix image src
  put in correct view counts from e.g. google analytics upon recreation. ?Maybe somethign like the instructions at?: https://developers.google.com/analytics/devguides/reporting/core/v4/choosing_which_version_of_the_analytics_reporting_api_to_use
